version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@types/node"
    versions:
    - "> 12.11.5, < 12.12"
  - dependency-name: "@types/node"
    versions:
    - "> 12.12.3, < 12.13"
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.1
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
